### ISSUE TITLE
Interagte with activiti 6

### ISSUE THREAD

**Issue by minhquankq** [lovromazgon/activiti-hashed-passwords#1]
It's not an issue, but, I don't where I can post this concern.
I want to handle _hash password_ in activiti 6, as your guideline, I should update `activiti-custom-context.xml` to set `customSessionFactories` to `processEngineConfiguration`. Where can I set in activiti-app in activiti6?

Thanks.

**Comment by lovromazgon** [comment]
I'm afraid I can't help you with that. I've taken a look at the source code of Activiti 6 and the classes which were used to implement user management are all gone, so this solution is incompatible with Activiti 6. You'll have to find another way.
